### PR TITLE
Configure prompt and display

### PR DESCRIPTION
**Pull request by fjakobs**
check https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_web_server_flow.htm&language=en_US for reference

### CODE REVIEW

**Comment by fjakobs** [comment]
@joshbirk

**Comment by joshbirk** [comment]
Merging - though note that I'll probably need to update the package.json file later, I just realized we aren't really conforming to npm standards.

**Comment by joshbirk** [comment]
Or not, might OK on the next publish.

**Comment by fjakobs** [comment]
@joshbirk awesome! Also thanks for pushing a new version to NPM.

**Pull request merged**
